### ISSUE TITLE
Fails to load channels, error says missing `short_channel_id`

### ISSUE THREAD

**Issue by niftynei** [Fonta1n3/Plasma#1]
Some of my CLN channels (listed in `listpeerchannels`) dont' have a `short_channel_id` field, so Plasma is failing to load.

Channels don't get a short_channel_id until the opening transaction is mined into a block, so it's possible for a entry to not have one.

**Comment by Fonta1n3** [comment]
Thanks for the issue and apologies for the long delay, will get it fixed for the next update asap.
