### ISSUE TITLE
KeyNotFound error

### ISSUE THREAD

**Issue by w035h** [Fonta1n3/Plasma#4]
I am getting this error when opening Plasma. Node is running as usual but there is a disconnected Channel waiting to be closed. 

keyNotFound (CodingKeys(stringValue:
"short_channel_id", intValue: nil),
Swift.DecodingError.Context(coding-
Path: [CodingKeys(string Value:
"channels",
", int Value: nil),
_JSONKey(string Value: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(string Value:
\"short_channel_id\", intValue: nil)
(\"short_channel_id\").", underlying Error: nil))

**Comment by Fonta1n3** [comment]
Thanks for the issue! Are you using Plasma via the App Store or TestFlight?

**Comment by Fonta1n3** [comment]
v1.0.7 (live soon) should fix the issue, if it does please come back and close this out.

**Comment by w035h** [comment]
I think we can close this. I’m not getting the error anymore in 1.0.7. The app is however crashing when I am scrolling trough the node info. Can you put 1.0.7 in TestFlight as well so I can share the info?  Probably a separate issue.

**Comment by w035h** [comment]
I think we can close this. I’m not getting the error anymore in 1.0.7. The app is however crashing when I am scrolling trough the node info. Can you put 1.0.7 in TestFlight as well so I can share the info?  Probably a separate issue.

**Comment by Fonta1n3** [comment]
Let's keep it open bc it's probably another similar error.

Are you using a restricted rune? Latest cln version?

**Comment by w035h** [comment]
Okay, thanks for the follow up. The rune is unrestricted. And I am on CLN v23.08.1. Might be helpful to know I have one pending Chanel close. The crash happens if I scroll down in the  ide info Tab. 

edit: when going to channels and peers I get this error. same for the request or pay buttons;




Error keyNotFound(CodingKeys(stringValue:
"owner", intValue: nil),
Swift.DecodingError.Context(coding-
Path: [CodingKeys(stringValue:
"channels", intValue: nil),
_JSONKey (string Value: "Index 0", intValue: 0)], debugDescription: "No value associated with key
CodingKeys(stringValue: \"owner\", intValue: nil) (\"owner\").", underlying Error: nil))

**Comment by Fonta1n3** [comment]
I don't have a pending close to test on but v1.0.8 should fix these, please keep reporting back with any bug you find, thanks.

**Comment by w035h** [comment]
All fixed! No more crashes. Tnx for the quick fixes. 👍

**Comment by w035h** [comment]
I just updated the app and there is still some funny stuff going on. The purple dot should show "Our balance" but the value is "Their balance" Looks like these should be switched around. The values for Spendable and Receivable are however correct.
