### ISSUE TITLE
Channel information is not displayed correctly

### ISSUE THREAD

**Issue by w035h** [Fonta1n3/Plasma#5]
Hi @Fonta1n3, I noticed that the Channel information is not displayed correctly. Somehow the balance on both sides is zero. I'm on CLN 24.02.2 and Plasma V1.0.8 

![IMG_7447](https://github.com/Fonta1n3/Plasma/assets/107932415/da93370d-cd34-4571-91b9-bf2068fd58c5)

**Comment by Fonta1n3** [comment]
Thanks, can't believe I missed that.. Should be all good in v1.0.9

**Comment by w035h** [comment]
lol, it happens. Looking forward to the update.

**Comment by w035h** [comment]
I just updated the app and there is still some funny stuff going on. The purple dot should show "Our balance" but the value is "Their balance" Looks like these should be switched around. The values for Spendable and Receivable are however correct.

**Comment by Fonta1n3** [comment]
ah another good find, my amounts were identical on both sides so didn't notice. Pushing 1.0.10 with a fix.

**Comment by w035h** [comment]
Followed up with another quick fix. Way to go! 👍
